### ISSUE TITLE
Zainicjować projekt

### ISSUE THREAD

**Issue by pktiuk** [KNR-PW/discord-bot#1]
- Wrzucenie podstawowej wersji projektu może być bot hello world
- Opisanie readme.md z instrukcjami budowania i odpalania

**Comment by PiotrWeppo** [comment]
Podstawowy bot już jest, jeszcze plik readme.md do zrobienia

**Comment by pktiuk** [comment]
![image](https://user-images.githubusercontent.com/45544416/203850425-08220ea7-776c-4bfe-9231-247f7b8209f6.png)

No jeszcze tego nie zrobiliśmy mój drogi.  
Issue zamyka się dopiero po zmergowaniu

**Comment by PiotrWeppo** [comment]
Nie doprecyzowałeś, ale świetny meme xd

**Comment by pktiuk** [comment]
No i teraz możesz sobie przypisać kolejne issue do zrobienia
