### ISSUE TITLE
Zdefiniowanie prostego formatu w jakim mamy opisywać templatki wiadomości

### ISSUE THREAD

**Issue by pktiuk** [KNR-PW/discord-bot#3]
Trzeba wymyślić jak mamy opisywać interaktywne obiekty np

```
Na tym serwerze jest {number @Rekrut} Rekrutów
```
Co bot już sobie z łatwością przekształci do wiadomości docelowej

```
Na tym serwerze jest 11 Rekrutów
```

**Comment by pktiuk** [comment]
Inna przykładowa wiadomość, jaka mnie interesuje:

```
Zarząd koła:

Prezez: @Jan kowalski (tutaj wypisuje teggo co ma rolę @Prezes)

Aktywni członkowie: 10
@ziomek1 @ziomek2 @ziomek3.... @ziomek10

Weteranowie: 3
@weteran1 @weteran2 @weteran3
```

**Comment by PiotrWeppo** [comment]
Na razie są takie możliwe komendy:
![chrome_RsgWWBAXNh](https://user-images.githubusercontent.com/117805804/215595826-9602ec04-fe1f-4a6d-be42-d6e10ec657d2.png)

**Comment by pktiuk** [comment]
Dużo tych komend zdefiniowałeś i nie jestem pewien, czy wszystkie są na ten moment potrzebne. Je wszystkie sam wypisałeś?

**Comment by pktiuk** [comment]
Jeszcze jeden sidenote, o którym zapomniałem zapisać bezpośrednio. Potrzebna jest też opcja na jakieś warunki logiczne przy zliczaniu ludzi oraz ich wypisywaniu. Tzn. Np aktywni członkowie koła to są wszystkie osoby na serwerze z wyłączeniem osób z rolą `@weteran`.

**Comment by pktiuk** [comment]
Jak będą wyglądać same wiadomości? Możesz podrzucić jakiś przykład?

```
tak btw to jeśli chcesz coś wpisać w bloku kodu taki blok zaczyna się ``` i tak samo się kończy (od nowej linii)

````


Jeśli nie wiesz jak to polecam spojrzeć na to jak się często formatuje tekst w pythonie z pomocą funkcji `format()`

```py
 txt = "For only {price:.2f} dollars!"
print(txt.format(price = 49)) 
##> For only 49.00 dollars!
```

**Comment by PiotrWeppo** [comment]
> Dużo tych komend zdefiniowałeś i nie jestem pewien, czy wszystkie są na ten moment potrzebne. Je wszystkie sam wypisałeś?

Sam. Nie pracuję z nikim nas tym botem. To są wszystkie, które byłem w stanie wyciągnąć, albo wydały mi się interesujące. Do Ciebie należy decyzja, co z tego potrzebujecie

**Comment by PiotrWeppo** [comment]
> Jeszcze jeden sidenote, o którym zapomniałem zapisać bezpośrednio. Potrzebna jest też opcja na jakieś warunki logiczne przy zliczaniu ludzi oraz ich wypisywaniu. Tzn. Np aktywni członkowie koła to są wszystkie osoby na serwerze z wyłączeniem osób z rolą `@weteran`.

Da się zrobić, ale najlepiej by było gdybym mógł go wtedy zintegrować z prywatnym kanałem na waszym serwerze. Serwer na którym teraz pracuję jest goły, więc trudniej jest testować bardziej złożone funkcje.

**Comment by pktiuk** [comment]
Zrobione, format wiadomości jest ładnie opisany w Readme
