### ISSUE TITLE
Przygotowanie podstawowego bota

### ISSUE THREAD

**Issue by pktiuk** [KNR-PW/discord-bot#8]
Lista TODO:

- [x] Stworzenie bota, który publikuje wiadomość na jakimś kanale i ią aktualizuje co jakiś czas. https://github.com/KNR-PW/discord-bot/pulls
- [x] Odczytywanie przez bota ról (od teraz ta aktualizowana wiadomość musi zawierać jakieś statystyki dotyczące osób z danymi rolami)
- [x] Zdefiniowanie prostego formatu w jakim mamy opisywać templatki wiadomości #3
- [x] Dodanie możliwości zmiany konfiguracji bota z poziomu czatu discordowego (ogólnie ogarnięcie komend)
  - [x] dodanie komendy `help`, która pokaże użytkownikowi jakąś prostą pomoc
  - [ ] dodanie jakiejś komendy do regulowania częstotliwości odświeżania 
  - [x] umożliwienie użytkownikowi ustawienie oraz wygodną zmianę tekstu wiadomości
- [x] Generowanie wiadomości z wykorzystaniem tego formatu templatki wiadomości.
- [x] posprzątanie kodu (jeśli coś będzie do posprzątania)

**Comment by PiotrWeppo** [comment]
Pierwszy i w pewnym stopniu drugi podpunkt zrobiony.

Problem z przejściem github action, albo zadowolę Pylint + flake8, albo Black'a.

W pierwszej wersji kod był bardzo czytelny:
![Code_coDWbeccX3](https://user-images.githubusercontent.com/117805804/214434803-59d7a8eb-efa0-4fd3-b314-28f48b49439c.png)

Po zreformatowaniu i skróceniu długości linii trudno coś w nim rozczytać. Jeśli zostawić aktualny stan, to trzeba będzie tak czy tak, pewnie nadpisać zasady długości wierszy w pylint i flake8, albo dodać wyjątki do black'a.

**Comment by pktiuk** [comment]
> Pierwszy i w pewnym stopniu drugi podpunkt zrobiony.

Jeśli pierwszy jest zrobiony to zmień status PRa i go zmergujemy.

> Po zreformatowaniu i skróceniu długości linii trudno coś w nim rozczytać

Nie tykaj konfiguracji formatowania. Kod ma być zawsze sformatowany bez wyjątków. Co najwyżej ja potem poprawię reguły formatowania, ale na pewno nie zmieniamy długości linii.

**Comment by PiotrWeppo** [comment]
Podaj przykład do tego fragementu:
"od teraz ta aktualizowana wiadomość musi zawierać jakieś statystyki dotyczące osób z danymi rolami"

**Comment by pktiuk** [comment]
```
Liczba osób z rolą @PR: 4
Aktywni członkowie Koła (czyli wszyscy, którzy nie mają roli @Weteran): 40
```
Ale patrząc po screenshotach i po kodzie wnioskuję, że już odczytujesz dane z ról, więc sprawdzenie tego typu danych to banał.

**Comment by pktiuk** [comment]
Teraz zdefiniuj format wiadomości (to zadanie na początku nie wymgaga kodowania, musisz w oddzielnym issue zaproponować jakiś format w którym mogę chcieć definiować wiadomość.

**Comment by pktiuk** [comment]
@PiotrWeppo 
Najważniejsza część zadania jest już skończona.  
Teraz w sumie pozostało tylko:

- podzielenie kodu na kilka plików
- ogólne ogarnięcie
- naprawienie warningów z pylinta
- Regulacja czasu odświeżania

Jest to już taka trochę opcjonalna rzecz, ale i tak warta zrobienia

**Comment by PiotrWeppo** [comment]
> * Regulacja czasu odświeżania

Czy napewno tego chcesz? Wyobrażam sobie, że ta opcja zostanie raz lub dwa razy dobrana przy odpalaniu bota i potem nikt już do niej nie wróci, a wiąże się to z zamianą jednego wiersza w kodzie więc nie wiem czy jest sens pisać specjalną komendę.

**Comment by pktiuk** [comment]
Tą regulację można sobie odpuścić

**Comment by pktiuk** [comment]
Zadanie wykonane w zupełności
